### ISSUE TITLE
Please add hacktoberfest topic to your repo

### ISSUE THREAD

**Issue by salob** [geerlingguy/ansible-role-node_exporter#7]
By clicking on the cog beside `About` and adding `hacktoberfest` topic to the repo, any contributors can gain points for hacktoberfest. See more info here: https://hacktoberfest.digitalocean.com/

Thanks!

<img width="443" alt="image" src="https://user-images.githubusercontent.com/8070665/137530899-244cdf88-e134-479b-ac01-99db6e5e6333.png">

**Comment by geerlingguy** [comment]
Thanks for the suggestion, but at this time I'm not participating in Hacktoberfest for any of my repos, as it requires a bit of extra bandwidth and I'm not able to take that on.
